import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import fs from "node:fs";
import path from "node:path";
import JSZip from "jszip";

/* On every build, emit luxe-rebuild-paste.txt (all sources, marker-delimited)
   so the owner can paste the project back after a server reset. */
/* Root-level files to include in the paste file. */
/* package-lock.json is intentionally excluded here (regenerated by `npm install`);
   it IS included in the downloadable luxe-source-code.zip. */
const PASTE_ROOT = ["package.json", "tsconfig.json", "vite.config.js", "index.html", "LOCK.md", "lock.json"];
/* Directories to walk recursively (relative to project root). */
const PASTE_DIRS = ["src", "public"];

/** Recursively list every file under a directory, as forward-slash paths
    relative to the project root. */
function walk(absDir, root, out) {
  for (const name of fs.readdirSync(absDir)) {
    const abs = path.join(absDir, name);
    const st = fs.statSync(abs);
    if (st.isDirectory()) walk(abs, root, out);
    else if (st.isFile()) out.push(path.relative(root, abs).split(path.sep).join("/"));
  }
  return out;
}
/** Every file that should go into the paste file, in a stable order. */
function pasteFiles() {
  const root = process.cwd();
  const files = [...PASTE_ROOT];
  for (const d of PASTE_DIRS) {
    const abs = path.resolve(root, d);
    if (fs.existsSync(abs)) walk(abs, root, files);
  }
  return files.sort();
}

function luxeRebuildPaste() {
  return {
    name: "luxe-rebuild-paste",
    generateBundle() {
      const lines = [
        "LUXE HAIR STUDIO — REBUILD PASTE FILE",
        "Paste this whole document into the chat after a server reset.",
        "The assistant splits on the `=== FILE: <path> ===` markers and recreates",
        "every file verbatim. Do not alter the markers or the code between them.",
        "",
      ];
      let included = 0;
      for (const rel of pasteFiles()) {
        const abs = path.resolve(process.cwd(), rel);
        if (!fs.existsSync(abs)) continue;
        lines.push(`=== FILE: ${rel} ===`);
        lines.push(fs.readFileSync(abs, "utf8").replace(/\n$/, ""));
        lines.push("");
        included++;
      }
      lines.push(`=== END (${included} files) ===`);
      this.emitFile({ type: "asset", fileName: "luxe-rebuild-paste.txt", source: lines.join("\n") });
    },
  };
}

/* Package the COMPILED production site (index.html + hashed JS/CSS + public
   files) into luxe-compiled-site.zip on every build. Unzip and host anywhere. */
function luxeCompiledSite() {
  return {
    name: "luxe-compiled-site",
    async generateBundle(_options, bundle) {
      const zip = new JSZip();
      const root = zip.folder("luxe-hair-studio-site");
      for (const [fileName, entry] of Object.entries(bundle)) {
        if (fileName === "luxe-rebuild-paste.txt" || fileName === "luxe-compiled-site.zip") continue;
        if (entry.type === "asset") {
          root.file(fileName, typeof entry.source === "string" ? entry.source : new Uint8Array(entry.source));
        } else if (entry.type === "chunk") {
          root.file(fileName, entry.code);
        }
      }
      for (const rel of ["robots.txt", "sitemap.xml"]) {
        const abs = path.resolve(process.cwd(), "public", rel);
        if (fs.existsSync(abs)) root.file(rel, fs.readFileSync(abs, "utf8"));
      }
      root.file("README-DEPLOY.txt", [
        "LUXE HAIR STUDIO — COMPILED SITE",
        "This ZIP is the production build, exactly as served. It is static & self-contained.",
        "",
        "TO DEPLOY: unzip, upload the contents of 'luxe-hair-studio-site' to any static host",
        "(Netlify, Vercel, S3, cPanel) at the DOMAIN ROOT, or run `npx serve` in the folder.",
        "",
        "NOTE: do not open index.html by double-clicking — browsers block ES-module apps",
        "from file://. Serve it over http (npx serve / python3 -m http.server 4173).",
      ].join("\n"));
      const buf = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
      this.emitFile({ type: "asset", fileName: "luxe-compiled-site.zip", source: new Uint8Array(buf) });
    },
  };
}

/* Serve the verified production build from dist/ through the dev server.
   The preview only reliably serves the app shell + /assets/ of the COMPILED
   build; dev module URLs (/src/*.tsx) break the in-browser site packager
   (nothing to collect) and are less stable overall. Auto-(re)builds when
   dist is missing or stale relative to the sources. */
function luxeServeDist() {
  return {
    name: "luxe-serve-dist",
    async configureServer(server) {
      const root = process.cwd();
      const distDir = path.resolve(root, "dist");
      const distIndex = path.join(distDir, "index.html");
      const needsBuild = () => {
        if (!fs.existsSync(distIndex)) return true;
        try {
          const distM = fs.statSync(distIndex).mtimeMs;
          return ["src/main.tsx", "index.html", "vite.config.js", "src/App.tsx"].some((p) => {
            const f = path.resolve(root, p);
            return fs.existsSync(f) && fs.statSync(f).mtimeMs > distM;
          });
        } catch { return false; }
      };
      if (needsBuild()) {
        try {
          const { execSync } = await import("node:child_process");
          console.log("[luxe] dist missing/stale — building the production bundle…");
          execSync("npx vite build", { stdio: "inherit" });
        } catch (e) {
          console.warn("[luxe] auto-build failed; falling back to live dev transforms.", e);
        }
      }
      server.middlewares.use((req, res, next) => {
        if (req.method !== "GET" && req.method !== "HEAD") return next();
        let pathname = (req.url || "/").split("?")[0];
        try { pathname = decodeURIComponent(pathname); } catch { /* keep raw */ }
        if (pathname.startsWith("/@") || pathname.startsWith("/__vite") ||
            pathname.startsWith("/node_modules") || pathname.startsWith("/src")) return next();
        let file = path.join(distDir, pathname === "/" ? "index.html" : pathname);
        if (!fs.existsSync(file) || fs.statSync(file).isDirectory()) file = distIndex;
        if (!fs.existsSync(file)) return next();
        const ext = path.extname(file).toLowerCase();
        const MIME = { ".html": "text/html; charset=utf-8", ".js": "application/javascript", ".mjs": "application/javascript", ".css": "text/css", ".txt": "text/plain; charset=utf-8", ".json": "application/json", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".svg": "image/svg+xml", ".ico": "image/x-icon", ".woff": "font/woff", ".woff2": "font/woff2", ".zip": "application/zip" };
        res.setHeader("Content-Type", MIME[ext] || "application/octet-stream");
        res.setHeader("Cache-Control", "no-store");
        if (ext === ".zip") res.setHeader("Content-Disposition", `attachment; filename="${path.basename(file)}"`);
        res.end(fs.readFileSync(file));
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), luxeRebuildPaste(), luxeCompiledSite(), luxeServeDist()],
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("node_modules")) {
            if (id.includes("@mediapipe")) return "vision_bundle";
            if (id.includes("three")) return "three_bundle";
            if (id.includes("gsap")) return "gsap_bundle";
            if (id.includes("jszip")) return "jszip.min";
          }
        },
      },
    },
  },
  server: {
    host: "0.0.0.0",
    port: 3000,
    strictPort: true,
    hmr: { port: 3000 },
  },
});
